<a href="https://colab.research.google.com/github/dapapko/HSE_Data_Analysis/blob/main/exercises_done.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Python

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


### Блок №1  
Исправьте код ниже, чтобы был такой же вывод, как под комментарием

In [ ]:
print("I'm a student and I'll become a \"strong\" programmer") #I'm a student and I'll become a "strong" programmer
# Ваш код здесь

print('C:\\Users\\GoodStudent') #C:\Users\GoodStudent
# Ваш код здесь

x = "My name is Agent Smith"
print(x[1]) #y
# Ваш код здесь

print(x[3:-4:3]) #nesgt
# Ваш код здесь

I'm a student and I'll become a "strong" programmer
C:\Users\GoodStudent
y
nesgt



### Блок №2

Запрос ввода осуществляется вызовом функции input(). В функцию можно передать строку, которая будет выведена на экран для общения с пользователем, например:

input('Введите ваш возраст')

Ввод пользователя возвращается функцией input в виде строки и может быть присвоен переменной:

age = input('Введите ваш возраст')

Функция input возвращает строку (даже если пользователь ввёл число). Чтобы сконвертировать строку к целому числу, можно сделать следующее:


In [ ]:
age_str = input('Введите ваш возраст') # age_str это строка
age = int(age_str) # age это int

Напишите код для следующих 2 задач:

In [ ]:
import math
#1. Клиент покупает кофе в кафе. За каждые 6 чашек, 1 чашка даётся в качестве бонуса.
#Задача: запросить у пользователя кол-во чашек на покупку, вычислить полагающееся кол-во бонусных чашек кофе и вывести это число через print().
# Ваш код здесь
cups = int(input("Введите количество чашек: "))
print(f'Количество бонусных чашек: {cups // 6}')

#2. Запросить у пользователя координаты x и y двух точек на плоскости. Посчитать расстояние между заданными точками и вывести результат.
#Примечание: у каждой точки есть две координаты: x и y. Расстояние рассчитывается по формуле, которую вы с лёгкостью найдёте в Интернете.
coords = input("Введите координаты точек через пробел (пример для точек A(6;2) и B(3;-1) : 6 2 3 -1)\n")
coords = list(map(float, coords.split()))
dist = math.sqrt((coords[2] - coords[0])**2 + (coords[1] - coords[3])**2)
print(f'Task #2 \nDistance: {dist}')

Введите количество чашек: 18
Количество бонусных чашек: 3
Введите координаты точек через пробел (пример для точек A(6;2) и B(3;-1) : 6 2 3 -1)
3 4 4 2
Task #2 
Distance: 2.23606797749979


### Блок №3 (Numpy)

Импортировать NumPy под именем np

In [ ]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Создать вектор размера 10, заполненный единицами

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Создать вектор размера 10, заполненный числом 2.5

In [ ]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [ ]:
arr = np.zeros(10)
arr[5] = 1
arr

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

Развернуть вектор (первый становится последним)

In [ ]:
arr = np.random.rand(10)
print(f'Original: {arr}')
print(f"Reversed: {arr[::-1]}")

Original: [0.34072972 0.73049351 0.55255271 0.68795428 0.74192235 0.47718916
 0.92683123 0.57039509 0.88587811 0.9899197 ]
Reversed: [0.9899197  0.88587811 0.57039509 0.92683123 0.47718916 0.74192235
 0.68795428 0.55255271 0.73049351 0.34072972]


Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [ ]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [ ]:
vector = [1,2,0,0,4,0]
np.nonzero(vector)

(array([0, 1, 4]),)

Создать 3x3 единичную матрицу

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Создать массив 3x3x3 со случайными значениями

In [ ]:
np.random.rand(3,3,3)

array([[[0.13681912, 0.71094763, 0.90080954],
        [0.07163221, 0.04961238, 0.21525934],
        [0.85823764, 0.06096179, 0.80311688]],

       [[0.42403721, 0.47812   , 0.57278313],
        [0.74574751, 0.94136984, 0.277976  ],
        [0.92310093, 0.82080993, 0.94788423]],

       [[0.41506115, 0.11417892, 0.29726908],
        [0.73452819, 0.22938813, 0.48811086],
        [0.65816432, 0.75091084, 0.53639577]]])

Перемножить матрицы 5x3 и 3x2

In [ ]:
m1 = np.random.rand(5,3)
m2 = np.random.rand(3,2)
print(m1)
print(m2)
np.dot(m1, m2)

[[0.21539719 0.11661563 0.50085137]
 [0.02945896 0.99175904 0.96278405]
 [0.87253362 0.42938812 0.18924197]
 [0.78572136 0.40025116 0.76987542]
 [0.64786265 0.17070456 0.43291086]]
[[0.99682453 0.25855279]
 [0.68395901 0.43291219]
 [0.26201227 0.87326282]]


array([[0.42570271, 0.54355075],
       [0.95994917, 1.27772479],
       [1.21303051, 0.57674133],
       [1.25869851, 1.04872763],
       [0.87598826, 0.61945174]])

Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

---


Зададим случайный вектор $(a_1,a_2,a_3,...,a_{10})^T$

In [ ]:
# Generate random number from (0;1)
def rng():
  while True:
    num = np.random.random_sample()
    if num !=0:
      return num

arr = np.asarray([ rng() for x in range (0,10) ])
print(arr)

[0.82425599 0.77104432 0.90686559 0.57299168 0.24218514 0.66414057
 0.68145735 0.86577026 0.94288768 0.7144421 ]


Заменить максимальный элемент на ноль

In [ ]:
arr[np.argmax(arr)] = 0
arr

array([0.82425599, 0.77104432, 0.90686559, 0.57299168, 0.24218514,
       0.66414057, 0.68145735, 0.86577026, 0.        , 0.7144421 ])

Преобразовать массив из float в int

In [ ]:
arr = np.random.random_sample(5)
print(arr)
arr.astype(dtype='int')

[0.20274226 0.21561627 0.92745666 0.49390028 0.41243355]


array([0, 0, 0, 0, 0])

Найти наиболее частое значение в массиве







In [ ]:
arr = np.asarray([2,3,3,4,5,-1,-1,-5.3, 2])
unique, counts = np.unique(arr,return_counts=True)
print(unique[ counts.argmax() ])

-1.0


Найти n наибольших значений в массиве

In [ ]:
n = 2
arr = np.asarray([2,3,3,4,5,-1,-1,-5.3, 2])
arr.sort()
arr[-n:]

array([4., 5.])

### Блок №4 (Pandas)

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts). Скачать датасет на свой компьютер и распаковать. Считать csv файл в датафрейм food:

In [ ]:
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)
pd.set_option('precision', 2)

import pandas as pd
food=pd.read_csv('/content/drive/My Drive/data/en.openfoodfacts.org.products.tsv',sep='\t', low_memory=False)

Посмотреть первые 5 записей

In [ ]:
display(food.head())

code                                                url  \
0  0000000003087  http://world-en.openfoodfacts.org/product/0000...   
1  0000000004530  http://world-en.openfoodfacts.org/product/0000...   
2  0000000004559  http://world-en.openfoodfacts.org/product/0000...   
3  0000000016087  http://world-en.openfoodfacts.org/product/0000...   
4  0000000016094  http://world-en.openfoodfacts.org/product/0000...   

                      creator   created_t      created_datetime  \
0  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z   
1             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
2             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
3             usda-ndb-import  1489055731  2017-03-09T10:35:31Z   
4             usda-ndb-import  1489055653  2017-03-09T10:34:13Z   

  last_modified_t last_modified_datetime                    product_name  \
0      1474103893   2016-09-17T09:18:13Z              Farine de blé noir   
1      1489069957   2017-03-09T14:32:37Z  Banana Chips Sweetened (Whole)   
2      1489069957   2017-03-09T14:32:37Z                         Peanuts   
3      1489055731   2017-03-09T10:35:31Z          Organic Salted Nut Mix   
4      1489055653   2017-03-09T10:34:13Z                 Organic Polenta   

  generic_name quantity packaging packaging_tags           brands  \
0          NaN      1kg       NaN            NaN  Ferme t'y R'nao   
1          NaN      NaN       NaN            NaN              NaN   
2          NaN      NaN       NaN            NaN   Torn & Glasser   
3          NaN      NaN       NaN            NaN        Grizzlies   
4          NaN      NaN       NaN            NaN   Bob's Red Mill   

       brands_tags categories categories_tags categories_en origins  \
0  ferme-t-y-r-nao        NaN             NaN           NaN     NaN   
1              NaN        NaN             NaN           NaN     NaN   
2     torn-glasser        NaN             NaN           NaN     NaN   
3        grizzlies        NaN             NaN           NaN     NaN   
4   bob-s-red-mill        NaN             NaN           NaN     NaN   

  origins_tags manufacturing_places manufacturing_places_tags labels  \
0          NaN                  NaN                       NaN    NaN   
1          NaN                  NaN                       NaN    NaN   
2          NaN                  NaN                       NaN    NaN   
3          NaN                  NaN                       NaN    NaN   
4          NaN                  NaN                       NaN    NaN   

  labels_tags labels_en emb_codes emb_codes_tags first_packaging_code_geo  \
0         NaN       NaN       NaN            NaN                      NaN   
1         NaN       NaN       NaN            NaN                      NaN   
2         NaN       NaN       NaN            NaN                      NaN   
3         NaN       NaN       NaN            NaN                      NaN   
4         NaN       NaN       NaN            NaN                      NaN   

  cities cities_tags purchase_places stores countries    countries_tags  \
0    NaN         NaN             NaN    NaN     en:FR         en:france   
1    NaN         NaN             NaN    NaN        US  en:united-states   
2    NaN         NaN             NaN    NaN        US  en:united-states   
3    NaN         NaN             NaN    NaN        US  en:united-states   
4    NaN         NaN             NaN    NaN        US  en:united-states   

    countries_en                                   ingredients_text allergens  \
0         France                                                NaN       NaN   
1  United States  Bananas, vegetable oil (coconut oil, corn oil ...       NaN   
2  United States  Peanuts, wheat flour, sugar, rice flour, tapio...       NaN   
3  United States  Organic hazelnuts, organic cashews, organic wa...       NaN   
4  United States                                    Organic polenta       NaN   

  allergens_en traces traces_tags traces_en     s

Сколько наблюдений в наборе данных?


In [ ]:
print(len(food))

356027


Сколько столбцов в наборе данных?

In [ ]:
print(len(food.columns))

163


Напечатайте все названия столбцов

In [ ]:
for c in food.columns:
  print(c)

code
url
creator
created_t
created_datetime
last_modified_t
last_modified_datetime
product_name
generic_name
quantity
packaging
packaging_tags
brands
brands_tags
categories
categories_tags
categories_en
origins
origins_tags
manufacturing_places
manufacturing_places_tags
labels
labels_tags
labels_en
emb_codes
emb_codes_tags
first_packaging_code_geo
cities
cities_tags
purchase_places
stores
countries
countries_tags
countries_en
ingredients_text
allergens
allergens_en
traces
traces_tags
traces_en
serving_size
no_nutriments
additives_n
additives
additives_tags
additives_en
ingredients_from_palm_oil_n
ingredients_from_palm_oil
ingredients_from_palm_oil_tags
ingredients_that_may_be_from_palm_oil_n
ingredients_that_may_be_from_palm_oil
ingredients_that_may_be_from_palm_oil_tags
nutrition_grade_uk
nutrition_grade_fr
pnns_groups_1
pnns_groups_2
states
states_tags
states_en
main_category
main_category_en
image_url
image_small_url
energy_100g
energy-from-fat_100g
fat_100g
saturated-fat_100g
-buty

Какое название у 105 столбца?

In [ ]:
print(food.columns[105])

-fructose_100g


Какой тип наблюдений в 105 столбце?

In [ ]:
print(food.dtypes[105])

float64


Каково значение имени продукта в 19-м наблюдении?

In [ ]:
food.iloc[19]['product_name']

'Organic Oat Groats'

### Блок №5 (Pandas - фильтрация данных)

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [ ]:
import pandas as pd
import json
import re
chipo = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv", sep='\t')
print(chipo)

      order_id  ...  item_price
0            1  ...      $2.39 
1            1  ...      $3.39 
2            1  ...      $3.39 
3            1  ...      $2.39 
4            2  ...     $16.98 
...        ...  ...         ...
4617      1833  ...     $11.75 
4618      1833  ...     $11.75 
4619      1834  ...     $11.25 
4620      1834  ...      $8.75 
4621      1834  ...      $8.75 

[4622 rows x 5 columns]


Как много продуктов стоят более чем $10.00?

In [ ]:
for i in chipo.index:
    chipo.at[i, "item_price"] = float(chipo.at[i, "item_price"][1:])

In [ ]:
print(len(chipo[chipo["item_price"] > 10.00]))    

1130


Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [ ]:
display(chipo[["item_name", "item_price"]])

item_name item_price
0              Chips and Fresh Tomato Salsa       2.39
1                                      Izze       3.39
2                          Nantucket Nectar       3.39
3     Chips and Tomatillo-Green Chili Salsa       2.39
4                              Chicken Bowl      16.98
...                                     ...        ...
4617                          Steak Burrito      11.75
4618                          Steak Burrito      11.75
4619                     Chicken Salad Bowl      11.25
4620                     Chicken Salad Bowl       8.75
4621                     Chicken Salad Bowl       8.75

[4622 rows x 2 columns]

Сколько было заказано самого дорогого предмета?

In [ ]:
# Get most expensive item
expensive = chipo.sort_values('item_price').iloc[-1]
result_df = chipo[chipo['item_name'].astype(str).str.contains(expensive['item_name'])]
print(result_df['quantity'].sum())      

130


Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [ ]:
result_df = chipo[chipo['item_name'].astype(str).str.contains("Veggie Salad Bowl")]
print(result_df['quantity'].sum())     

18


Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [ ]:
df = chipo[chipo['item_name'].astype(str).str.contains("Canned Soda")]
print(len(df[df['quantity'] > 1]))

20
